version: "3"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  app-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "home-service-db"

  home-service:
    build: .
    image: home_service:latest
    ports:
      - "8000:8000"
    depends_on:
      - "app-db"
    command:
      [
        "./wait-for-it.sh",
        "app-db:5432",
        "--",
        "make",
        "complete-run"
      ]
    environment:
      - DB_HOST=app-db
      - DB_PORT=5432
