from django.urls import path
from home_service.dependency_injection import dependency_injector
from .views import *

app_name = "services"
service_view = dependency_injector.service_view

urlpatterns = [
    path(
        "request/<int:role_id>",
        service_view.request_service_from_expert,
        name="request_service_from_expert",
    ),
    path(
        "request",
        service_view.request_service_from_system,
        name="request_service_from_system",
    ),
    path(
        "request/delete/<int:request_id>",
        service_view.delete_request,
        name="delete_request"
    ),
    path(
        "request/admin_create",
        service_view.request_service_for_customer,
        name="create_requset_by_admin"
    ),
    path(
        "approve/<int:request_id>",
        service_view.approve_request,
        name="approve_request",
    ),
    path(
        "reject/<int:request_id>",
        service_view.reject_request,
        name="reject_request",
    ),
    path(
        "accept-expert/<int:request_id>",
        service_view.accept_expert,
        name="reject_request",
    ),
    path(
        "finish/<int:request_id>",
        service_view.finish_request,
        name="finish_request",
    ),
    path(
        "experts/list",
        service_view.experts_list,
        name="experts_list",
    ),
    path(
        "list",
        service_view.services_list,
        name="services_list",
    ),
    path(
        "<int:service_id>",
        service_view.service,
        name="service_update"
    ),
    path(
        "delete/<int:service_id>", 
        service_view.delete_service, 
        name="service_delete"
    ),
    path(
        "",
        service_view.create_service,
        name="service_create"
    ),
    path(
        "request/finding",
        service_view.finding_expert,
        name="finding_expert",
    ),
    path(
        "categories",
        service_view.categories_list,
        name="categories_list",
    ),
    path(
        "category/<int:category_id>",
        service_view.category,
        name="category_update",
    ),
    path(
        "category/delete/<int:category_id>",
        service_view.delete_category,
        name="category_delete",
    ),
    path(
        "category",
        service_view.create_category,
        name="category_create"
    ),
    path(
        "limitations",
        service_view.limitations_list,
        name="limitations_list",
    ),
    path(
        "limitation/<int:limitation_id>",
        service_view.limitation,
        name="limitation_update",
    ),
    path(
        "limitation/delete/<int:limitation_id>",
        service_view.delete_limitation,
        name="limitation_delete",
    ),
    path(
        "limitation",
        service_view.create_limitation,
        name="limitation_create"
    ),

]
